jobs:
  include:
    - dist: xenial
      os: linux
    - dist: bionic
      os: linux
    - os: winsows
    - os: osx
language: rust
rust:
  - stable
  - 1.42.0
  - 1.44.0
  - 1.46.0
cache: cargo
os: linux
dist: xenial

before_install:
  - export FILE_ROOT="rustkdb"
  - export TESTS="True"
  ## Setup q
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      QLIBDIR=w64; OD=$W64;
    elif [[ $TRAVIS_OS_NAME == "linux" ]]; then
      QLIBDIR=l64; OD=$L64;
    elif [[ $TRAVIS_OS_NAME == "osx" ]]; then
      QLIBDIR=m64; OD=$M64;
    else
      echo "unknown OS ('$TRAVIS_OS_NAME')" >&2; exit 1;
    fi
  - export QLIBDIR
  - mkdir q
  - export QHOME=q
  - export PATH=${PATH}:${QHOME}/${QLIBDIR}
  - echo $QHOME > qhome.txt
  - cat qhome.txt
  - echo $PATH > path.txt
  - cat path.txt
  - if [[ $TESTS == "True" && "$OD" != "" && "$QLIC_KC" != "" ]]; then
      curl -u $NEXUS_USER:$NEXUS_PASS -o ${QHOME}/q.zip -L $OD;
      unzip -d ${QHOME}/ ${QHOME}/q.zip;
      rm ${QHOME}/q.zip;
      echo -n $QLIC_KC |base64 --decode > ${QHOME}/kc.lic;
    else
      echo No kdb+, no tests;
    fi
  - ls -l q
  - ls -l ${QHOME}/${QLIBDIR}
  - echo ${PATH}
script:
  - cargo build --release
  ## Start q process on 5000
  - ./travistest.sh
  - cat qtest.log
  ## Clean up file
  - rm qtest.log
notifications:
  slack: kxsys:oDr1mgvVq4ztmPXalwUs4Gio